### ISSUE TITLE
The requested module 'pdfjs-dist' does not provide an export named 'PasswordResponses'

### ISSUE THREAD

**Issue by ndrbrt** [hrynko/vue-pdf-embed#209]
I just tried the basic example in the README and got this error:

```bash
 ERROR  The requested module 'pdfjs-dist' does not provide an export named 'PasswordResponses'

  import { PasswordResponses } from "pdfjs-dist";
  ^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'pdfjs-dist' does not provide an export named 'PasswordResponses'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
  at async ViteNodeRunner.interopedImport (node_modules/@nuxt/vite-builder/node_modules/vite-node/dist/client.mjs:383:28)
  at async ViteNodeRunner.directRequest (node_modules/@nuxt/vite-builder/node_modules/vite-node/dist/client.mjs:253:24)
  at async ViteNodeRunner.cachedRequest (node_modules/@nuxt/vite-builder/node_modules/vite-node/dist/client.mjs:189:14)
  at async ViteNodeRunner.dependencyRequest (node_modules/@nuxt/vite-builder/node_modules/vite-node/dist/client.mjs:233:12)
  at async pages/pdf.vue:1:31
  at async ViteNodeRunner.runModule (node_modules/@nuxt/vite-builder/node_modules/vite-node/dist/client.mjs:362:5)
  at async ViteNodeRunner.directRequest (node_modules/@nuxt/vite-builder/node_modules/vite-node/dist/client.mjs:346:5)
```

- Node v20.11.1
- pdfjs-dist v3.11.174
- vue-pdf-embed v2.0.3

**Comment by ndrbrt** [comment]
It turns out that this error occurs only in SSR mode. Forcing client-side rendering solves the problem. My bad.

**Comment by clarkio** [comment]
@ndrbrt I'm running into the same issue with Astro. How did you force client-side rendering for your project? In Astro I set `client:load` but I'm still running into this error.

**Comment by ndrbrt** [comment]
@clarkio I'm not familiar with Astro. In Vue+Nuxt I used `<ClientOnly>`
```vue
<ClientOnly>
  <VuePdfEmbed ... />
</ClientOnly>
```
