### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by anonimQwerty** [hrynko/vue-pdf-embed#54]
ReferenceError: self is not defined
    at Object.<anonymous> (D:\site\node_modules\vue-pdf-embed\dist\vue3-pdf-embed.js:1:252)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async __instantiateModule__ (file:///D:/site/.nuxt/dist/server/server.mjs:7113:3)

nuxt3 node 17

**Comment by hrynko** [comment]
Hi @anonimQwerty,

I assume this to be a duplicate of one of those: #12 or #21. Please reopen if it is not.
